Repository pymc-devs/pytensor, pull requests merged in 2022-11, with the labels that each got.

#28 Optimize Scan inner graph when compiling to Numba
  pytensor/link/numba/dispatch/scan.py
  tests/link/numba/test_scan.py
Labels: bug, numba, scan

#42 Add plain issue template
  .github/ISSUE_TEMPLATE/plain.yml
Labels: maintenance

#47 Update issue templates
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/developer.yml
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/installation.yml
  .github/ISSUE_TEMPLATE/plain.yml
Labels: maintenance, no releasenotes
