Repository pymc-devs/pytensor, pull requests merged in 2023-07, with the labels that each got.

#370 Don't run useless fusion and inplace rewrites in JAX mode
  pytensor/compile/mode.py
Labels: jax, maintenance, graph rewriting

#383 Fix bug in `tag_solve_triangular` rewrite
  pytensor/tensor/rewriting/linalg.py
  tests/tensor/rewriting/test_linalg.py
Labels: bug, graph rewriting, linalg

#391 Drop support for Python 3.8
  .github/workflows/test.yml
  pyproject.toml
Labels: major, release

#394 Speedup `truncated_graph_inputs`
  .github/workflows/test.yml
  environment.yml
  pyproject.toml
  pytensor/graph/basic.py
  tests/graph/test_basic.py
Labels: bug

#398 Unify signatures of `graph_replace` and `clone_replace`
  pytensor/compile/function/pfunc.py
  pytensor/graph/replace.py
  tests/graph/test_replace.py
Labels: maintenance

#400 Don't include `local_uint_constant_indices` rewrite in JAX mode due to XLA bug
  pytensor/compile/mode.py
Labels: bug, jax, graph rewriting

#402 Fix overly strict check in `local_pow_specialize` rewrite
  pytensor/tensor/rewriting/math.py
Labels: bug

#403 Provide JAX Ops from Optional tensorflow-probability dependency
  .github/workflows/test.yml
  pytensor/link/jax/dispatch/scalar.py
  tests/link/jax/test_scalar.py
Labels: enhancement, jax
