Repository pymc-devs/pytensor, pull requests merged in 2023-03, with the labels that each got.

#228 Rename `sgn` with `sign`
  doc/library/sparse/index.rst
  doc/library/tensor/basic.rst
  pytensor/compile/profiling.py
  pytensor/scalar/basic.py
  pytensor/sparse/basic.py
  pytensor/tensor/inplace.py
  pytensor/tensor/math.py
  pytensor/tensor/rewriting/math.py
  pytensor/tensor/subtensor.py
  tests/sparse/test_basic.py
  tests/tensor/rewriting/test_math.py
  tests/tensor/test_inplace.py
  tests/tensor/test_math.py
Labels: maintenance

#236 Fix scan save memory rewrite bug
  pytensor/scan/rewriting.py
  tests/scan/test_rewriting.py
Labels: bug, graph rewriting, scan

#238 Fix numpy DeprecationWarning when converting integers to PyTensor Constants
  pytensor/misc/safe_asarray.py
Labels: maintenance

#251 Fix JAX erfinv failing test
  tests/link/jax/test_scalar.py
Labels: jax, maintenance, no releasenotes, tests

#242 Allow string keys in `eval` utility
  pytensor/graph/basic.py
  tests/graph/test_basic.py
Labels: enhancement

#248 `get_scalar_constant_value` now raises for non-scalar inputs
  doc/library/tensor/basic.rst
  pytensor/__init__.py
  pytensor/gradient.py
  pytensor/link/jax/dispatch/tensor_basic.py
  pytensor/scan/basic.py
  pytensor/scan/rewriting.py
  pytensor/tensor/basic.py
  pytensor/tensor/blas.py
  pytensor/tensor/conv/abstract_conv.py
  pytensor/tensor/elemwise.py
  pytensor/tensor/exceptions.py
  pytensor/tensor/extra_ops.py
  pytensor/tensor/random/op.py
  pytensor/tensor/rewriting/basic.py
  pytensor/tensor/rewriting/elemwise.py
  pytensor/tensor/rewriting/math.py
  pytensor/tensor/rewriting/shape.py
  pytensor/tensor/rewriting/subtensor.py
  pytensor/tensor/shape.py
  pytensor/tensor/subtensor.py
  pytensor/tensor/var.py
  tests/sparse/test_basic.py
  tests/tensor/test_basic.py
  tests/tensor/test_elemwise.py
  tests/tensor/test_math.py
Labels: bug

#260 Raise NotImplementedError when trying to convert MaskedArrays
  pytensor/scalar/basic.py
  pytensor/tensor/sharedvar.py
  tests/tensor/test_basic.py
  tests/tensor/test_sharedvar.py
Labels: bug

#261 Fix a typo in Graph Rewriting Doc
  doc/extending/graph_rewriting.rst
Labels: docs
