Repository pymc-devs/pytensor, pull requests merged in 2023-11, with the labels that each got.

#485 Fix memory leak in TensorFromScalar
  pytensor/tensor/basic.py
Labels: bug, C-backend, aesara downstream

#493 Add `set` and `add` TensorVariable methods for `set_subtensor` and `inc_subtensor` operations`
  pytensor/tensor/variable.py
  tests/tensor/test_variable.py
Labels: enhancement

#494 Add `set` and `add` TensorVariable methods for `set_subtensor` and `inc_subtensor` operations`
  pytensor/tensor/variable.py
  tests/tensor/test_variable.py
Labels: docs

#496 Defer the use of nfunc_spec in JAX scalar dispatch
  pytensor/link/jax/dispatch/scalar.py
Labels: jax, maintenance

#498 Implement JAX dispatch for TriGamma
  pytensor/link/jax/dispatch/scalar.py
  tests/link/jax/test_scalar.py
Labels: enhancement, jax, backend compatibility

#490 Implement ChiSquare via Gamma
  doc/library/tensor/random/basic.rst
  pytensor/link/numba/dispatch/random.py
  pytensor/tensor/random/basic.py
  pytensor/tensor/random/rewriting/jax.py
Labels: maintenance, major

#503 Rename `add` `inc_subtensor` helper method to `inc`
  pytensor/tensor/variable.py
  tests/tensor/test_variable.py
Labels: maintenance

#505 Implement Polygamma Op
  pytensor/gradient.py
  pytensor/scalar/math.py
  pytensor/tensor/math.py
  pytensor/tensor/rewriting/math.py
  tests/link/jax/test_scalar.py
  tests/tensor/rewriting/test_math.py
  tests/tensor/test_math.py
Labels: graph rewriting, Op implementation, SciPy compatibility

#507 Fix deprecation wrapper for vectorize_graph
  pytensor/graph/replace.py
Labels: bug, no releasenotes

#454 Vectorize dispatch for shape operations
  pytensor/graph/replace.py
  pytensor/tensor/blockwise.py
  pytensor/tensor/elemwise.py
  pytensor/tensor/shape.py
  tests/tensor/test_shape.py
Labels: bug, enhancement

#506 Use empty blas_ldflags if no cxx is configured
  pytensor/link/c/cmodule.py
  tests/link/c/test_cmodule.py
Labels: bug, C-backend

#510 Do not merge while scans with different until condition
  pytensor/scan/rewriting.py
  tests/scan/test_rewriting.py
Labels: bug, graph rewriting, scan

#519 Fix vectorized shape
  pytensor/tensor/shape.py
  tests/tensor/test_shape.py
Labels: bug

#522 Include C cache preloading in profile output
  pytensor/compile/function/types.py
  pytensor/compile/profiling.py
Labels: maintenance, C-backend

#520 Faster vectorize by walking sorted nodes
  pytensor/graph/replace.py
Labels: enhancement

#521 Faster `infer_static_shape`
  pytensor/tensor/basic.py
  pytensor/tensor/rewriting/basic.py
  pytensor/tensor/rewriting/math.py
  pytensor/tensor/rewriting/shape.py
  pytensor/tensor/rewriting/subtensor.py
  pytensor/tensor/shape.py
  scripts/mypy-failing.txt
Labels: maintenance, compilation speed
