Repository pymc-devs/pytensor, pull requests merged in 2023-12, with the labels that each got.

#528 Add _logger.debug statements to cmodule default blas ldflags
  pytensor/link/c/cmodule.py
Labels: maintenance

#484 Extend sum of mul rewrite for multiple axis
  pytensor/tensor/rewriting/math.py
  tests/tensor/rewriting/test_elemwise.py
  tests/tensor/rewriting/test_math.py
Labels: graph rewriting, computational speed

#536 Improve PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no releasenotes, release

#543 Add Exponentially scaled modified Bessel Op
  pytensor/link/jax/dispatch/scalar.py
  pytensor/scalar/math.py
  pytensor/tensor/inplace.py
  pytensor/tensor/math.py
  tests/tensor/test_math_scipy.py
Labels: enhancement, Op implementation, SciPy compatibility

#533 Add aliases for arithmetic inequality function equivalents in NumPy
  doc/library/tensor/basic.rst
  pytensor/tensor/math.py
Labels: maintenance, NumPy compatibility

#550 Do not generate C code for BatchedDot when BLAS flags are missing
  pytensor/tensor/blas.py
  tests/tensor/test_blas.py
Labels: bug, C-backend, graph rewriting

#553 Implement `vectorize_node` for `CheckAndRaise` `Op`
  pytensor/raise_op.py
  tests/test_raise_op.py
Labels: enhancement, vectorization

#557 Update vectorize_graph docstring
  pytensor/graph/replace.py
Labels: docs

#554 Show duration of slowest tests in CI
  .github/workflows/test.yml
Labels: GitHub CI/CD, no releasenotes

#558 Add rewrite for matmul when only one of the inputs has batched dimensions
  pytensor/tensor/rewriting/math.py
  tests/tensor/rewriting/test_math.py
Labels: enhancement, graph rewriting, computational speed, vectorization
