Repository pymc-devs/pytensor, pull requests merged in 2023-02, with the labels that each got.

#184 Spell-check the repository
  doc/extending/creating_a_c_op.rst
  doc/extending/creating_an_op.rst
  doc/extending/scan.rst
  doc/library/tensor/random/utils.rst
  doc/scripts/docgen.py
  doc/tutorial/shape_info.rst
  pytensor/compile/function/types.py
  pytensor/compile/profiling.py
  pytensor/configdefaults.py
  pytensor/graph/replace.py
  pytensor/graph/rewriting/db.py
  pytensor/link/numba/dispatch/elemwise_codegen.py
  pytensor/link/numba/dispatch/scalar.py
  pytensor/link/numba/dispatch/scan.py
  pytensor/misc/ordered_set.py
  pytensor/misc/pkl_utils.py
  pytensor/scan/op.py
  pytensor/tensor/basic.py
  pytensor/tensor/rewriting/basic.py
  pytensor/tensor/subtensor.py
  tests/tensor/random/test_op.py
  tests/tensor/rewriting/test_math.py
  tests/tensor/rewriting/test_subtensor.py
  tests/tensor/test_subtensor.py
Labels: no releasenotes

#205 Fix `pt.stack` type hints
  pytensor/tensor/basic.py
  tests/tensor/test_basic.py
Labels: enhancement

#186 Rewrite products of exponents as exponent of sum
  pytensor/tensor/rewriting/math.py
  tests/tensor/rewriting/test_math.py
Labels: enhancement, graph rewriting

#206 Propagate static shape in MaxAndArgmax
  pytensor/tensor/math.py
  tests/tensor/test_math.py
Labels: enhancement, static shape

#213 Add pyupgrade to pre-commit and apply it
  .pre-commit-config.yaml
  pytensor/compile/mode.py
  pytensor/gradient.py
  pytensor/graph/fg.py
  pytensor/graph/op.py
  pytensor/graph/rewriting/basic.py
  pytensor/link/c/cmodule.py
  pytensor/link/numba/dispatch/elemwise_codegen.py
  pytensor/printing.py
  pytensor/sparse/type.py
  pytensor/tensor/random/rewriting/basic.py
  pytensor/tensor/random/utils.py
  pytensor/tensor/slinalg.py
  pytensor/tensor/type.py
  tests/link/numba/test_scan.py
Labels: maintenance

#214 Fix DeprecationWarning from scipy.sparse.base
  pytensor/sparse/basic.py
Labels: maintenance

#225 Fix spurious warning from FusionOptimizer
  pytensor/tensor/rewriting/elemwise.py
  tests/tensor/rewriting/test_elemwise.py
Labels: bug
