Repository pymc-devs/pytensor, pull requests merged in 2024-03, with the labels that each got.

#645 Implement `tensor.special.logit` helper
  pytensor/tensor/special.py
  tests/tensor/test_special.py
Labels: enhancement, SciPy compatibility

#657 Add JAX support for SortOp
  pytensor/link/jax/dispatch/tensor_basic.py
  tests/link/jax/test_tensor_basic.py
Labels: enhancement, jax, backend compatibility

#659 Prevent `local_sum_make_vector` from introducing forbidden `float64`
  pytensor/tensor/rewriting/basic.py
  tests/tensor/rewriting/test_basic.py
Labels: bug, graph rewriting

#664 Handle implicit broadcasting correctly in RandomVariable vectorization
  pytensor/tensor/random/op.py
  pytensor/tensor/random/utils.py
  tests/tensor/random/test_op.py
Labels: bug, random variables, vectorization

#668 prevent `log10` `L_op` from upcasting
  pytensor/scalar/basic.py
  tests/scalar/test_basic.py
Labels: maintenance, Op implementation

#675 Remove numba-scipy dependency
  .github/workflows/test.yml
  environment.yml
  pyproject.toml
Labels: maintenance, numba

#676 Allow defining an OpFromGraph from constant and shared inputs
  pytensor/compile/builders.py
  tests/compile/test_builders.py
Labels: enhancement, major, graph objects, Op implementation

#628 Make Constant and Shared variables subclasses of the respective Variables
  pytensor/sparse/basic.py
  pytensor/sparse/sharedvar.py
  pytensor/tensor/sharedvar.py
Labels: maintenance, major, graph objects

#681 Fix bug when broadcasting branches in local_useless_switch rewrite
  pytensor/tensor/rewriting/basic.py
  tests/tensor/rewriting/test_basic.py
Labels: bug, graph rewriting
