Repository pymc-devs/pytensor, pull requests merged in 2024-04, with the labels that each got.

#686 Remove TopkOp
  pytensor/tensor/__init__.py
  pytensor/tensor/rewriting/basic.py
  pytensor/tensor/sort.py
  tests/tensor/test_sort.py
Labels: major

#678 Ensure that gcc path is only added once to DLL search path
  pytensor/link/c/cmodule.py
Labels: bug, C-backend

#692 Pin Numpy version to <2
  pyproject.toml
Labels: maintenance, NumPy compatibility

#699 Cleanup OpFromGraph tests
  tests/compile/test_builders.py
Labels: no releasenotes, tests, OpFromGraph

#706 Fix mypy problem on Windows due to platform differences
  pytensor/link/c/cmodule.py
Labels: maintenance, no releasenotes, pre-commit

#702 Added support for matrix_transpose
  pytensor/tensor/basic.py
  pytensor/tensor/rewriting/linalg.py
  pytensor/tensor/variable.py
  tests/tensor/test_basic.py
Labels: enhancement, NumPy compatibility

#704 Only invoke config.cxx if non-empty
  pytensor/configdefaults.py
Labels: bug, C-backend

#720 Add codecov_token env variable to upload coverage report
  .github/workflows/test.yml
Labels: GitHub CI/CD, no releasenotes

#724 Avoid dimshuffle if expand_dims has empty axis
  pytensor/tensor/basic.py
Labels: maintenance

#717 Reconcile environment for development and docs building
  doc/dev_start_guide.rst
  doc/environment.yml
  doc/scripts/docgen.py
  environment.yml
Labels: docs, maintenance

#726 Remove deprecated bin module
  .pre-commit-config.yaml
  MANIFEST.in
  bin/__init__.py
  bin/pytensor-cache
  bin/pytensor_cache.py
  doc/extending/pipeline.rst
  pyproject.toml
Labels: maintenance

#729 Improve variable debugging methods
  pytensor/graph/basic.py
  tests/graph/test_basic.py
Labels: maintenance

#614 Implement gradient for SVD
  pytensor/tensor/nlinalg.py
  tests/tensor/test_nlinalg.py
Labels: enhancement, gradients, linalg

#712 Add helper `explicit_graph_inputs`
  pytensor/graph/basic.py
  tests/graph/test_basic.py
Labels: enhancement
