Repository pymc-devs/pytensor, pull requests merged in 2024-01, with the labels that each got.

#567 Revert "Bump actions/download-artifact from 3 to 4"
  .github/workflows/pypi.yml
  .github/workflows/test.yml
Labels: no releasenotes, dependencies

#502 Implement betaincinv and gammainc[c]inv functions
  pytensor/link/jax/dispatch/scalar.py
  pytensor/scalar/math.py
  pytensor/tensor/inplace.py
  pytensor/tensor/math.py
  pytensor/tensor/special.py
  tests/link/jax/test_scalar.py
  tests/tensor/test_math_scipy.py
  tests/tensor/test_special.py
Labels: enhancement, Op implementation, SciPy compatibility

#566 Fix bug where ShapeFeature would create circular shape graph
  pytensor/tensor/rewriting/shape.py
  tests/tensor/rewriting/test_shape.py
Labels: bug, shape problem, graph rewriting

#571 Vectorize softmax and argmax nodes
  pytensor/tensor/basic.py
  pytensor/tensor/elemwise.py
  pytensor/tensor/math.py
  pytensor/tensor/shape.py
  pytensor/tensor/special.py
  tests/tensor/test_math.py
  tests/tensor/test_special.py
Labels: enhancement, vectorization

#575 Remove incorrect `solve` usage in `psd_solve_with_chol` rewrite
  pytensor/tensor/rewriting/linalg.py
  tests/tensor/rewriting/test_linalg.py
Labels: bug, graph rewriting, linalg

#576 Add `linalg.block_diag` and sparse equivalent
  pytensor/link/jax/dispatch/slinalg.py
  pytensor/link/numba/dispatch/slinalg.py
  pytensor/sparse/basic.py
  pytensor/tensor/basic.py
  pytensor/tensor/slinalg.py
  tests/link/jax/test_slinalg.py
  tests/link/numba/test_slinalg.py
  tests/sparse/test_basic.py
  tests/tensor/test_slinalg.py
Labels: enhancement, Op implementation, SciPy compatibility, sparse variables, linalg

#570 Fix `vectorize_graph` bug when replacements were provided for only some outputs of a node
  pytensor/graph/basic.py
  pytensor/graph/replace.py
  tests/graph/test_basic.py
  tests/graph/test_replace.py
Labels: bug, vectorization

#574 Don't store `fortran` objects in `ScipyGer` tag
  pytensor/tensor/blas.py
  pytensor/tensor/blas_scipy.py
  scripts/mypy-failing.txt
  tests/tensor/test_blas_scipy.py
Labels: bug

#587 Fix bug in storage_input alignment of the JAX backend
  pytensor/link/jax/linker.py
  tests/link/jax/test_random.py
Labels: bug, jax, random variables

#594 Add background section of fork history
  README.rst
Labels: docs

#593 Loosen versioneer version requirement from exact to min version
  pyproject.toml
Labels: maintenance

#597 Apply pyupgrade fixes missing from ruff
  pytensor/compile/profiling.py
  pytensor/graph/rewriting/basic.py
  pytensor/link/utils.py
  pytensor/tensor/rewriting/elemwise.py
Labels: maintenance, pre-commit

#598 Fix redefinitions
  pytensor/graph/basic.py
  pytensor/graph/rewriting/basic.py
  tests/tensor/test_math.py
Labels: maintenance, no releasenotes

#578 Implement numba overload for POTRF, LAPACK cholesky routine
  pytensor/link/numba/dispatch/basic.py
  pytensor/link/numba/dispatch/slinalg.py
  pytensor/tensor/slinalg.py
  tests/link/numba/test_nlinalg.py
  tests/link/numba/test_slinalg.py
Labels: enhancement, numba, computational speed, SciPy compatibility, linalg

#607 Fix tensordot implementation
  pytensor/tensor/math.py
  tests/tensor/test_math.py
Labels: bug

#602 Do not change global config flag in printing test
  tests/test_printing.py
Labels: bug, maintenance

#617 Replace usage of `sys.stdout.encoding` with `sys.getdefaultencoding()`
  pytensor/link/c/cmodule.py
Labels: bug, maintenance
