Repository pymc-devs/pytensor, pull requests merged in 2025-09, with the labels that each got.

#1602 Fix failure with narrowing of ssize_t to int in macos
  pytensor/tensor/elemwise.py
  pytensor/tensor/elemwise_cgen.py
Labels: bug, macOS, C-backend

#1600 Skip scan rewrites if there is no Scan Op in the graph
  pytensor/graph/rewriting/db.py
  pytensor/scan/rewriting.py
Labels: maintenance, graph rewriting, performance

#1520 Add `compiler_verbose` config flag
  doc/library/config.rst
  pytensor/configdefaults.py
  pytensor/configparser.py
  pytensor/link/numba/dispatch/basic.py
Labels: maintenance, compilation

#1585 Add intro notebook from workshop
  .pre-commit-config.yaml
  doc/gallery/introduction/pytensor_intro.ipynb
  pyproject.toml
Labels: docs
