Repository pymc-devs/pytensor, pull requests merged in 2025-03, with the labels that each got.

#1231 Allow `transposed` argument in `linalg.solve`
  pytensor/link/jax/dispatch/slinalg.py
  pytensor/link/numba/dispatch/slinalg.py
  pytensor/tensor/slinalg.py
  tests/link/jax/test_slinalg.py
  tests/link/numba/test_slinalg.py
  tests/tensor/test_slinalg.py
Labels: SciPy compatibility, linalg

#1267 Do not introduce 0 strides for broadcastable dimensions in DimShuffle
  pytensor/tensor/c_code/dimshuffle.c
  tests/tensor/test_elemwise.py
Labels: maintenance, C-backend

#1280 Remove `enable_slice_literals` function
  pytensor/link/numba/dispatch/basic.py
Labels: maintenance, numba

#1250 Expose vecdot, vecmat and matvec helpers
  pytensor/tensor/math.py
  tests/tensor/test_math.py
Labels: enhancement, NumPy compatibility

#1258 Allow passing numpy arrays to transpose
  pytensor/tensor/variable.py
  tests/tensor/test_variable.py
Labels: maintenance, NumPy compatibility

#1268 Speedup pytensor import time with lazy import of scipy.stats
  pytensor/tensor/random/basic.py
Labels: maintenance

#1291 Modify atleast_Nd to accept only one positional argument
  pytensor/tensor/basic.py
  tests/tensor/test_basic.py
Labels: maintenance, major

#1313 Add scipy-like `kn` helper
  pytensor/tensor/math.py
  tests/tensor/test_math_scipy.py
Labels: enhancement, SciPy compatibility

#1315 Simplify dispatch of JAX random variables by handling rng split automatically
  pytensor/link/jax/dispatch/random.py
  tests/link/jax/test_random.py
Labels: jax, major, random variables

#1314 Include Op in message when raising `NotImplementedError` from grad
  pytensor/graph/op.py
Labels: maintenance, gradients

#1302 Modify `arange` to directly determine the shape from the arguments if possible
  pytensor/tensor/basic.py
  tests/tensor/test_basic.py
Labels: shape inference

#1303 Implement gradient for QR decomposition
  pytensor/tensor/nlinalg.py
  tests/tensor/test_nlinalg.py
Labels: enhancement, gradients, linalg

#1318 Implement batched convolve1d
  pytensor/link/jax/dispatch/__init__.py
  pytensor/link/jax/dispatch/signal/__init__.py
  pytensor/link/jax/dispatch/signal/conv.py
  pytensor/link/numba/dispatch/__init__.py
  pytensor/link/numba/dispatch/signal/__init__.py
  pytensor/link/numba/dispatch/signal/conv.py
  pytensor/tensor/__init__.py
  pytensor/tensor/signal/__init__.py
  pytensor/tensor/signal/conv.py
  tests/link/jax/signal/__init__.py
  tests/link/jax/signal/test_conv.py
  tests/link/numba/signal/test_conv.py
  tests/tensor/signal/__init__.py
  tests/tensor/signal/test_conv.py
Labels: enhancement, SciPy compatibility, convolution

#1328 Fix nan for valid parameters in jax implementation of Multinomial
  pytensor/link/jax/dispatch/random.py
  tests/link/jax/test_random.py
Labels: bug, jax, random variables
