Repository pymc-devs/pytensor, pull requests merged in 2025-04, with the labels that each got.

#1335 Don't run local uint constant indices in C/Python backends
  pytensor/compile/mode.py
  pytensor/tensor/rewriting/subtensor.py
  pytensor/tensor/subtensor.py
Labels: maintenance, performance, indexing

#1339 More stable fix for JAX Multinomial
  pytensor/link/jax/dispatch/random.py
Labels: bug

#1309 Support numba compiled `sort` and `argsort` functions
  pytensor/link/numba/dispatch/basic.py
  tests/link/numba/test_basic.py
Labels: enhancement, numba

#1349 correct comparison in env yaml
  environment-osx-arm64.yml
Labels: no releasenotes

#1355 Allow specializing shape of predefined tensor types
  pytensor/tensor/type.py
  tests/tensor/test_type.py
Labels: enhancement

#1380 Restore d3viz/html/template.html
  pytensor/d3viz/html/template.html
Labels: maintenance

#1383 Use `PyObject_CallNoArgs` to call thunks from VM
  pytensor/link/c/c_code/lazylinker_c.c
  pytensor/link/c/lazylinker_c.py
Labels: maintenance, C-backend
