Repository pymc-devs/pytensor, pull requests merged in 2025-06, with the labels that each got.

#1435 Handle `compute_map=None` in Scan
  pytensor/scan/op.py
  tests/scan/test_basic.py
Labels: bug

#1456 Fix invalid numpy dtype
  pytensor/gradient.py
  pytensor/scalar/basic.py
  pytensor/sparse/rewriting.py
Labels: bug

#1182 Implement symbolic `minimize` and `root` `Ops`
  pytensor/tensor/optimize.py
  tests/tensor/test_optimize.py
Labels: enhancement, Op implementation, SciPy compatibility

#1329 Simplify Numba implementation of Alloc
  pytensor/link/numba/dispatch/tensor_basic.py
Labels: maintenance, numba

#1469 QoL improvements to InteractiveRewrite widget
  pytensor/ipython.py
Labels: no releasenotes

#1467 Reuse `cholesky` decomposition with `cho_solve` in graphs with multiple `pt.solve` when `assume_a = "pos"`
  pytensor/tensor/_linalg/solve/rewriting.py
  tests/tensor/linalg/test_rewriting.py
  tests/tensor/test_blockwise.py
Labels: enhancement, graph rewriting, performance, linalg

#1474 Fix optimize example notebook folder name
  doc/gallery/optimize/root.ipynb
Labels: docs

#1463 Correct indexing links in docs
  doc/library/tensor/basic.rst
  pytensor/tensor/subtensor.py
Labels: docs

#1482 Fix bug in gradient of Blockwise'd Scan
  pytensor/tensor/blockwise.py
  tests/tensor/test_blockwise.py
Labels: bug, gradients, scan, vectorization

#1470 Simplify typify of Generators in JAXLinker
  pytensor/link/jax/linker.py
Labels: jax, no releasenotes

#1487 Use lapack func instead of `scipy.linalg.cholesky`
  pytensor/tensor/slinalg.py
  tests/link/numba/test_slinalg.py
  tests/tensor/test_slinalg.py
Labels: maintenance, performance
